on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: docker setup buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker login (docker.io)
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker login (quay.io)
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ github.actor }}
          password: ${{ secrets.QUAY_TOKEN }}

      - id: decode_ref
        name: decode ref
        run: ./ci.sh decode-ref "${{ github.ref_name }}" >> "$GITHUB_OUTPUT"

      - id: meta
        name: docker metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            acicn/${{ steps.decode_ref.outputs.name }}
            ghcr.io/${{ github.repository }}/${{ steps.decode_ref.outputs.name }}
            quay.io/acicn/${{ steps.decode_ref.outputs.name }}
          tags: |
            type=raw,value=${{ steps.decode_ref.outputs.tag }}

      - name: docker build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ steps.decode_ref.outputs.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
